//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ephemera.MidiLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ephemera.MidiLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; The GM instrument patches.
        ///[instruments]
        ///000 = AcousticGrandPiano
        ///001 = BrightAcousticPiano
        ///002 = ElectricGrandPiano
        ///003 = HonkyTonkPiano
        ///004 = ElectricPiano1
        ///005 = ElectricPiano2
        ///006 = Harpsichord
        ///007 = Clavinet
        ///008 = Celesta
        ///009 = Glockenspiel
        ///010 = MusicBox
        ///011 = Vibraphone
        ///012 = Marimba
        ///013 = Xylophone
        ///014 = TubularBells
        ///015 = Dulcimer
        ///016 = DrawbarOrgan
        ///017 = PercussiveOrgan
        ///018 = RockOrgan
        ///019 = ChurchOrgan
        ///020 = ReedOrgan
        ///021 = Accordion
        ///022 = Harmonica
        ///023 = TangoAccordion [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gm_defs {
            get {
                return ResourceManager.GetString("gm_defs", resourceCulture);
            }
        }
    }
}
